CREATE TABLE "grants" (
	"id" serial PRIMARY KEY NOT NULL,
	"external_id" integer,
	"full_name" text NOT NULL,
	"programme_name" text NOT NULL,
	"agency" text,
	"website_url" text,
	"financing_type" text NOT NULL,
	"financing_type_category" text NOT NULL,
	"total_pool_raw" text,
	"total_pool_rm" bigint,
	"ticket_size_min_raw" text,
	"ticket_size_min_rm" bigint,
	"ticket_size_max_raw" text,
	"ticket_size_max_rm" bigint,
	"cost_of_capital_raw" text,
	"cost_of_capital_pct_min" numeric(5, 2),
	"cost_of_capital_pct_max" numeric(5, 2),
	"tenure_raw" text,
	"tenure_years_min" numeric(5, 1),
	"tenure_years_max" numeric(5, 1),
	"grace_period_raw" text,
	"grace_period_months" integer,
	"shariah_compliant" text,
	"value_chain_segments" text[],
	"permitted_uses" text[],
	"ownership_requirement_raw" text,
	"company_stage_raw" text,
	"collateral_raw" text,
	"application_cycle" text,
	"example_recipients" text,
	"notes" text,
	"last_synced_at" timestamp with time zone NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "grants_full_name_unique" UNIQUE("full_name")
);
